# Created by: Henry Hu <henry.hu.sh@gmail.com>
# $FreeBSD$

PORTNAME=	fcitx-table-other
PORTVERSION=	0.2.3
CATEGORIES=	textproc
MASTER_SITES=	http://download.fcitx-im.org/${PORTNAME}/
DIST_SUBDIR=	fcitx

MAINTAINER=	henry.hu.sh@gmail.com
COMMENT=	Table-based input methods for Fcitx

LICENSE=	GPLv3

LIB_DEPENDS=	libfcitx-config.so:chinese/fcitx

USES=		tar:xz cmake gettext
INSTALLS_ICONS=	yes
STRIP=

.include <bsd.port.mk>
